// <auto-generated />
using CarTest.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarTest.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20260224172909_AlterVehicleTypeToString")]
    partial class AlterVehicleTypeToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarTest.Entity.Car", b =>
                {
                    b.Property<int>("Vehicle_id")
                        .HasColumnType("int");

                    b.Property<int>("DoorsQuantity")
                        .HasColumnType("int");

                    b.HasKey("Vehicle_id");

                    b.ToTable("Car", (string)null);
                });

            modelBuilder.Entity("CarTest.Entity.Motorcycle", b =>
                {
                    b.Property<int>("Vehicle_id")
                        .HasColumnType("int");

                    b.Property<bool>("HasElectricStart")
                        .HasColumnType("bit");

                    b.HasKey("Vehicle_id");

                    b.ToTable("Motorcycle", (string)null);
                });

            modelBuilder.Entity("CarTest.Entity.Truck", b =>
                {
                    b.Property<int>("Vehicle_id")
                        .HasColumnType("int");

                    b.Property<decimal>("LoadCapacity")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Vehicle_id");

                    b.ToTable("Truck", (string)null);
                });

            modelBuilder.Entity("CarTest.Entity.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("CarTest.Entity.Car", b =>
                {
                    b.HasOne("CarTest.Entity.Vehicle", "Vehicle")
                        .WithOne("Car")
                        .HasForeignKey("CarTest.Entity.Car", "Vehicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTest.Entity.Motorcycle", b =>
                {
                    b.HasOne("CarTest.Entity.Vehicle", "Vehicle")
                        .WithOne("Motorcycle")
                        .HasForeignKey("CarTest.Entity.Motorcycle", "Vehicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTest.Entity.Truck", b =>
                {
                    b.HasOne("CarTest.Entity.Vehicle", "Vehicle")
                        .WithOne("Truck")
                        .HasForeignKey("CarTest.Entity.Truck", "Vehicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarTest.Entity.Vehicle", b =>
                {
                    b.Navigation("Car");

                    b.Navigation("Motorcycle");

                    b.Navigation("Truck");
                });
#pragma warning restore 612, 618
        }
    }
}
